from datetime import datetime


def generate_incident_report(ai_analysis: str, incident_summary: str) -> dict:

    report_id = f"RCA-{datetime.now().strftime('%Y%m%d-%H%M%S')}"

    report_markdown = f"""
# Incident Postmortem Report

**Report ID:** {report_id}
**Generated At:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**System:** E-commerce Checkout Platform
**Generated By:** RCA Copilot

---

## Incident Metrics Summary

{incident_summary}

---

## AI Root Cause Analysis

{ai_analysis}

---

## Review Notes

This report was generated using local AI and should be reviewed by an engineer before operational use.
"""

    return {
        "report_id": report_id,
        "report_markdown": report_markdown
    }